Sp 207 fix linter errors
shadow-robot/sr_tests pull request #10
Opened 2022-05-09 09:12 UTC by BenStarmerSmith

## Proposed changes

Fixed some linter errors in sr_tests.

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [x] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [] Manually tested on hardware (if hardware specific or related).

## Documentation

- [x] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2022-05-09 11:17 UTC, maxzieba requested changes, later dismissed

2022-05-09 11:17 UTC, maxzieba commented on sr_pose_tests/scripts/test_hand_poses.py
> +        poses_yaml_file_name = 'hand_poses_to_test_hand_e'  # pylint: disable=C0103
why the  pylint disable C0103? its in our naming convention

2022-05-09 11:17 UTC, maxzieba commented on sr_pose_tests/scripts/test_hand_poses.py
> +    for pose in srt._hand_trajectories:  # pylint: disable=W0212
within SrRunTrajectories please add a getter or make this the _hand_trajectories public

2022-05-10 13:55 UTC, biofotis approved these changes

2022-05-10 13:55 UTC, merged